version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - docker --version
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $ECR_REPO_URI

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t capstone-1:$IMAGE_TAG .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Tagging image...
      - docker tag capstone-1:$IMAGE_TAG $ECR_REPO_URI:$IMAGE_TAG
      - echo Pushing image to Amazon ECR...
      - docker push $ECR_REPO_URI:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
